# Generated by Django 6.0.6 on 2026-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('wishlist', 'Wish List'), ('birthday', 'Birthday')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
